### ISSUE TITLE
please check the recode

### ISSUE THREAD

**Issue by martinoli-f** [DataAccess2020/CE1_martinoli_travaglini#1]
@simonetravaglini1 Hi!! :)  I have just recoded the variables we need for our research. Can you please check the script2? 
Note that in the variable imp_rel I have inverted the values of the variable v6 in order to have an increasing scale (from "not at all important" to "very important"). I think it's better this way. let me know :)

**Comment by simonetravaglini1** [comment]
Dear @martinoli-f  I checked the work and I think it is the best recoding for what we have to do, since the dependent variable is also from the lowest to the highest value :)

**Comment by martinoli-f** [comment]
thank you @simonetravaglini1 ! :)
