### ISSUE TITLE
CE1_reg_model script issues

### ISSUE THREAD

**Issue by simonetravaglini1** [DataAccess2020/CE1_martinoli_travaglini#2]
hey @martinoli-f :) I created the regression model, but the probability output is in scientific notation, can you fix it? thx

**Comment by martinoli-f** [comment]
Dear Colleague @simonetravaglini1 , I fixed the problem with the output of the regression, please check the commit ca2cf4a :)

**Comment by simonetravaglini1** [comment]
thx a lot :)))
