### ISSUE TITLE
check the report.rmd 

### ISSUE THREAD

**Issue by martinoli-f** [DataAccess2020/CE1_martinoli_travaglini#4]
Hi @simonetravaglini1 :) sorry to bother you, I have just updated the Rmarkdown file with the report (I added the comparison between means and the conclusion). Can you please check it and give me your feedback?
In addition, I think we should find a better title for our project: what do you think about it? do you have some ideas? :)
At last, can you please add at the end the links of our sourches? 
Thank you :)

**Comment by simonetravaglini1** [comment]
hi @martinoli-f i checked the report and i think it's ok. for the title, what do you think if we titled it: religion and attitude towards euthanasia?

**Comment by martinoli-f** [comment]
yeah, I think it's great!! I have changed it :) thx
